"""Shared State definition for the HorRAGor Multi-Agent LangGraph architecture.

The State serves as the common memory between:
1. RAG Agent (Local Researcher)
2. Scraper Agent (Web Investigator)
3. Narration Agent (Gothic Writer)
"""

from typing import Annotated, Any
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class HorragorState(TypedDict, total=False):
    """The shared state passed through the LangGraph multi-agent pipeline."""

    # Original user query
    query: str

    # Extracted or corrected movie title (via FAISS similarity)
    extracted_title: str | None

    # Raw structured data retrieved by the RAG agent from FAISS and local database
    rag_data: dict[str, Any] | None

    # Web scraped content retrieved by the Scraper agent if local data is insufficient
    web_data: str | None

    # Routing condition: True if local FAISS/DB data is complete, False if web scraping is needed
    is_local_info_sufficient: bool

    # Trimmed factual summary (strict token isolation for the Narration Agent)
    context_summary: str | None

    # Final gothic narrative generated by the Gothic Writer Agent
    final_narrative: str | None

    # Currently active movie title across multi-turn conversation turns
    active_title: str | None

    # Multi-turn conversation history
    conversation_history: list[dict[str, Any]] | None

    # LangGraph message history (optional for conversational turns)
    messages: Annotated[list[BaseMessage], add_messages]
